/*
 * Project name:
     Ducati_logger.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     5/7/2013
 * Time of creation
     9:51:01 AM
 * Test configuration:
     MCU:             STM32F407ZG
     Dev.Board:       Mikromedia_Plus_for_STM32_ARM
                      http://www.mikroe.com/mikromedia/plus/stm32-m4/
     Oscillator:      150000000 Hz
     SW:              mikroC PRO for ARM
                      http://www.mikroe.com/mikroc/arm/
 */

#include "Ducati_logger_objects.h"

// external declarations
void RTC_Init();
char Init_FAT();
void Init_GPIO();


void main() {

  Init_GPIO();
  //Init_FAT();
  RTC_Init();
  Start_TP();


  while (1) {
    DisableInterrupts();
    Check_TP();
    EnableInterrupts();
  }
}
