/*
 * Project name:
     gif.vtft
 * Generated by:
     Visual TFT
 * Date of creation
     8/4/2012
 * Time of creation
     7:53:50 PM
 * Test configuration:
     MCU:             P33FJ256GP710A
     Dev.Board:       MikroMMB_for_dsPIC33_hw_rev_1.10
                      http://www.mikroe.com/eng/products/view/586/mikrommb-for-dspic33-board/
     Oscillator:      80000000 Hz
     SW:              mikroC PRO for dsPIC
                      http://www.mikroe.com/eng/products/view/231/mikroc-pro-for-dspic30-33-and-pic24/
 */

#include "gif_objects.h"

void main() {

  Start_TP();

  while (1) {
    //Check_TP();

  }

}
